# @file
# .travis.yml - Drupal Paranoia.

language: php

## Run on container environment
sudo: false

php:
  - 7.1

matrix:
  fast_finish: true

env:
  global:
    # Set the composer vendor Path.
    - COMPOSER_VENDOR_PATH="$HOME/.config/composer/vendor"

    # Add executables into PATH.
    - PATH="$PATH:$COMPOSER_VENDOR_PATH/bin"

    - SITE_NAME="mysite"
    - SITE_ROOT="$TRAVIS_BUILD_DIR/../$SITE_NAME"

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini

  # Update Composer.
  - composer self-update --stable
  - composer clear-cache

  # Install composer parallel install plugin.
  - composer global require hirak/prestissimo --no-interaction

  #  Install PHP Code Sniffer and Drupal Coding standards.
  - composer global require drupal/coder --prefer-dist -vvv || exit 1
  - phpcs --config-set installed_paths "$COMPOSER_VENDOR_PATH/drupal/coder/coder_sniffer"
  - phpcs --config-set ignore_warnings_on_exit 1

install:
  # Create Drupal project.
  - composer create-project drupal-composer/drupal-project:8.x-dev --stability dev --no-interaction --no-dev --prefer-dist -vvv "$SITE_ROOT" || exit 1

  # https://github.com/drupal-composer/drupal-paranoia#configuration
  - cd "$SITE_ROOT"; mv "$SITE_ROOT/web" "$SITE_ROOT/app"
  - sed -e "s?web/?app/?g" --in-place "$SITE_ROOT/composer.json"
  - cd "$SITE_ROOT"; composer config extra.drupal-app-dir app
  - cd "$SITE_ROOT"; composer config extra.drupal-web-dir web

  # Require local drupal-paranoia project.
  - cd "$SITE_ROOT"; composer config repositories.local_drupal_paranoia path "$TRAVIS_BUILD_DIR"
  - cd "$SITE_ROOT"; composer require --update-no-dev drupal-composer/drupal-paranoia:"*" -vvv || exit 1

script:
  # Run test script.
  - $TRAVIS_BUILD_DIR/.travis/test-script.sh

  # Sniff code standards.
  - phpcs --standard=Drupal --ignore=*.md,*.txt --warning-severity=0 -d date.timezone=UTC .
